swagger: '2.0'
info:
  title: Lemonade Stand API
  description: >
    This is an API for the Lemonade Stand game. It is used in a workshop and like making lemonade in real life, is a bit messy.
  version: 0.0.1
host: lemonade-stand.local
schemes:
  - http
basePath: /v1
produces:
  - application/json
paths:
  '/lemonade':
    get:
      tags:
        - supplies
      summary: Placeholder for Lemonade Top level
      operationId: getLemonade
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Lemonade'
              
  '/signs':
    get:
      tags:
        - supplies
      summary: Placeholder for Signs Top level
      operationId: getSigns
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Signs'
              
              
              
              
              
              
              
#  '/lemonade/{turn}':
#    post:
#      tags:
#        - supplies
#      summary: Set how many cups of lemonade to make
#      operationId: addItem
#      parameters:
#        - name: turn
#          in: path
#          description: The turn to set the quanity for
#          required: true
#          type: string
#        - name: quantity
#          description: How many cups to make
#          in: body
#          required: true
#          schema:
#            $ref: '#/definitions/Lemonade'
#      responses:
#        '201':
#          description: Quantity set

 
definitions:
  Lemonade:
    type: object
    properties:
      quantity:
        type: integer
       
  Signs:
    type: object
    properties:
      quantity:
        type: integer

 
